name: rotorsync_admin
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  flutter_launcher_icons: ^0.14.3
  lucide_icons: ^0.257.0
  http: ^1.3.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1
  uuid: ^4.5.1
  mqtt_client: ^10.5.1
  flutter_blue_plus: ^1.35.3
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "client/assets/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
